- php/class-query.php
This is configured in a CMB2 option.
> Add exclusion meta query for ebooks.

- php/class-shortcodes.php
Organised shortcodes by alphabetical order.
> Added featured image shortcodes (featured-image, featured-img)

- lifterlms/quiz/passing-percent.php
Fixes https://github.com/Yoast/yoast.com/issues/204
> If user is passing score dont show required percentage

- lifterlms/quiz/summary.php
Fixes https://github.com/Yoast/yoast.com/issues/203
> Added wpautop to content and description fields

- php/class-shortcodes.php
Removing shortcodes for aside and sidebar_content inside the sidebar_content will prevent this from happening again
> Sidebar content shortcode caused an infinite loop

- php/class-text-changes.php
Add videowrapper to vimeo video as well to make sure media page displays correctly on mobile.
> Extend domains for videowrapper embeds

- lifterlms/quiz/summary.php
- php/class-theme.php
Fixes https://github.com/Yoast/yoast.com/issues/267
> Add space between "Your answer" and the answer

- html_includes/partials/navigation-menu-link.php
- html_includes/partials/navigation-menu-list.php
- html_includes/partials/navigation-menu.php
- php/class-yoast-navigation.php
Unified function names, added comments, separated templates into own files.
Hopefully @diedexx has more time before launching new code to clean things up before committing next time ;)
> Restored sanity to the Navigation class

- html_includes/partials/affiliate-code.php
- html_includes/partials/affiliate-conversion.php
- php/class-affiliate.php
- php/class-theme.php
Fixes https://github.com/Yoast/my.yoast.com/issues/21
> Implement TapFilliate tracking code

- html_includes/partials/list-usp.php
- php/functions-helpers.php
Depends on https://github.com/Yoast/my.yoast.com/pull/95
Provides additional information that was available via meta data of a download.
> Use EDD_Client for product meta

- html_includes/shop/input-creditcard.php
Fixes https://github.com/Yoast/yoast.com/issues/422
> Added maxlength for month and year fields

- html_includes/shortcodes/plugin-stats.php
- php/functions-helpers.php
Remove comment of get_teplate_part when not admin or explicit debug in template vars
> Remove comments in code for visitors

- html_includes/partials/article-intro.php
- single-post.php
Fixes https://github.com/Yoast/yoast.com/issues/280
> Hide comments on overview when post has disabled them

- author.php
fixes https://github.com/Yoast/yoast.com/issues/530
> set excerpt "more" link before outputting it

- html_includes/partials/algolia-instantsearch.php
relies on https://github.com/Yoast/algolia-yoast-modifications/pull/2
> show modification date instead of post date

- css/sass/3-particles/_announcement-banner.scss
- php/class-theme-settings.php
Add styling for birthday banner
> Add styling for birthday banner

- php/class-theme.php
Fixes https://github.com/Yoast/yoast.com/issues/1001
> Inject VWO option script

- html_includes/emails/academy-invite.php
- html_includes/emails/academy-order-invite.php
Update emails for Yoast Academy
> Update mails for academy

- lifterlms/course/syllabus.php
> Allows non-admin users to view free lessons

- php/class-domains.php
- php/functions-links.php
used in https://github.com/Yoast/yoast.com/pull/1163
> added courses archive to domain class and link functions

- html_includes/partials/llms-registration-closed.php
- lifterlms/myaccount/form-login.php
Implemented copy changes as requested in https://github.com/Yoast/yoast.academy/issues/67
Fixes https://github.com/Yoast/yoast.academy/issues/67
> 67 copy tweaks to academy login page

- php/class-product-options-modal.php
fixes https://github.com/Yoast/yoast.com/issues/1296
relies on https://github.com/Yoast/yoast.com-ms/pull/162
> Dynamic bulk modal

- html_includes/partials/newsletter-subscribe.php
fixes https://github.com/Yoast/yoast.com/issues/1298
**How to test**
Check if copy is changed to "Get free SEO tips!"
> Changes copy

- php/class-product-options-modal.php
fixes https://github.com/Yoast/yoast.com/issues/1311
> switch blogs when getting dynamic pricing for bulk modal

- algolia/autocomplete.php
Fixes an error where the autocomplete wouldn't be triggered and causes an error
Fixes the width of the autocomplete so it is as wide as the search bar after it expands
Removes the `powered by Algolia` mark from the autocomplete
> Fix algolia autocomplete
